version: '3.9'
services:
  jaeger:
    image: jaegertracing/opentelemetry-all-in-one:latest
    ports:
      - "3001:16686"

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=root

  redis:
    image: "redis:alpine"
  bouncer:
    build:
      dockerfile: ./Dockerfile-dev
      context: .
    depends_on:
      - jaeger
      - postgres
      - redis
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - LOG_LEVEL=INFO
      - DATABASE_URL=postgres://postgres:root@postgres:5432/postgres
      - TELEMETRY_ENABLED=true
      - TELEMETRY_GRPC_URL=http://jaeger:4317
      - ATTESTATION_CACHE_URL=redis://redis:6379/0
